
# pip install python-okx
# pip install pandas
# pip install pandas-ta
# pip install pywin32

key = '37183f91-bb5e-43c7-ab98-979474209be9'
secret = '5AD20C1E094508003865FAA2B1B18E8D'
passw = '#-ffD7GnC*eL9k~'

"""
SPOT:
    USDT:
        BTC-USDT, ETH-USDT, OKB-USDT, LTC-USDT, XRP-USDT, BCH-USDT, SOL-USDT, ORDI-USDT, GAS-USDT, DOGE-USDT
        SHIB-USDT, FIL-USDT, 1INCH-USDT, AAVE-USDT, ACA-USDT, ACH-USDT, ADA-USDT, AERGO-USDT, AGLD-USDT
        AIDOGE-USDT, AKITA-USDT, ALCX-USDT, ALGO-USDT, ALPHA-USDT, ANT-USDT, APE-USDT, API3-USDT, APM-USDT
        APT-USDT, AR-USDT, ARB-USDT, ARG-USDT, AST-USDT, ASTR-USDT, ATOM-USDT, AUCTION-USDT, AVAX-USDT
        AXS-USDT, AZY-USDT, BABYDOGE-USDT, BADGER-USDT, BAL-USDT, BAND-USDT, BAT-USDT, BETH-USDT, BICO-USDT
        BIGTIME-USDT, BLOK-USDT, BLUR-USDT, BNB-USDT, BNT-USDT, BONE-USDT, BORING-USDT, BORA-USDT, BRWL-USDT
        BSV-USDT, BTT-USDT, BZZ-USDT, CAPO-USDT, CEEK-USDT, CELO-USDT, CEL-USDT, CELR-USDT, CETUS-USDT
        CFG-USDT, CFX-USDT, CGL-USDT, CHZ-USDT, CITY-USDT, CLV-USDT, COMP-USDT, CONV-USDT, CORE-USDT
        CQT-USDT, CRO-USDT, CRV-USDT, CSPR-USDT, CTC-USDT, CTXC-USDT, CVC-USDT, CVP-USDT, CVX-USDT, DAI-USDT
        DAO-USDT, DASH-USDT, DCR-USDT, DEP-USDT, DGB-USDT, DIA-USDT, DOME-USDT, DORA-USDT, DOSE-USDT, DOT-USDT
        DYDX-USDT, EGLD-USDT, ELF-USDT, ELON-USDT, EM-USDT, ENJ-USDT, ENS-USDT, EOS-USDT, ERN-USDT, ETC-USDT
        ETHW-USDT, EURT-USDT, FAME-USDT, FITFI-USDT, FLM-USDT, FLOW-USDT, FLOKI-USDT, FLR-USDT, FORTH-USDT
        FRONT-USDT, FSN-USDT, FTM-USDT, FXS-USDT, GALA-USDT, GALFT-USDT, GAL-USDT, GARI-USDT,GEAR-USDT
        GF-USDT, GFT-USDT, GHST-USDT, GLM-USDT, GLMR-USDT, GMT-USDT, GMX-USDT, GOAL-USDT, GODS-USDT, GOG-USDT
        GRT-USDT, HBAR-USDT, HC-USDT, ICP-USDT, ICX-USDT, ID-USDT, IGU-USDT, ILV-USDT, IMX-USDT, IOST-USDT
        IOTA-USDT, IQ-USDT, JOE-USDT, JPG-USDT, JST-USDT, KAN-USDT, KAR-USDT, KCAL-USDT, KDA-USDT, KINE-USDT
        KISHU-USDT, KLAY-USDT, KNC-USDT, KONO-USDT, KP3R-USDT, KSM-USDT, LAMB-USDT, LAT-USDT, LBR-USDT
        LDO-USDT, LEASH-USDT, LEO-USDT, LET-USDT, LHINU-USDT, LINK-USDT, LING-USDT, LITH-USDT, LON-USDT
        LOOKS-USDT, LPT-USDT, LQTY-USDT, LRC-USDT, LSK-USDT, LUNC-USDT, LUNA-USDT, MAGIC-USDT, MANA-USDT
        MASK-USDT, MATIC-USDT, MDT-USDT, MEME-USDT, MENGO-USDT, METIS-USDT, MILO-USDT, MINA-USDT, MKR-USDT
        MLN-USDT, MOVR-USDT, MOVEZ-USDT, MRST-USDT, MXC-USDT, MYRIA-USDT, NEAR-USDT, NEO-USDT, NFT-USDT
        NMR-USDT, NULS-USDT, NYM-USDT, OAS-USDT, OKT-USDT, OM-USDT, OMG-USDT, OMI-USDT, OMN-USDT, ONE-USDT
        ONT-USDT, OP-USDT, ORBS-USDT, ORB-USDT, OXT-USDT, PCI-USDT, PEOPLE-USDT, PEPE-USDT, PERP-USDT, PHA-USDT
        PIT-USDT, POLS-USDT, POLYDOGE-USDT, POR-USDT, PRQ-USDT, PSTAKE-USDT, QTUM-USDT, RACA-USDT, RADAR-USDT
        RAY-USDT, RDNT-USDT, REN-USDT, REP-USDT, REVV-USDT, RIO-USDT, RNDR-USDT, RON-USDT, RPL-USDT, RSR-USDT
        RSS3-USDT, RVN-USDT, SAMO-USDT, SAND-USDT, SC-USDT, SD-USDT, SIS-USDT, SKEB-USDT, SKL-USDT, SLP-USDT
        SNT-USDT, SNX-USDT, SPELL-USDT, SPURS-USDT, SSV-USDT, SSWP-USDT, STARL-USDT, STC-USDT, STETH-USDT
        STORJ-USDT, STX-USDT, SUI-USDT, SUN-USDT, SUSHI-USDT, SWEAT-USDT, SWFTC-USDT, T-USDT, TAKI-USDT
        TAMA-USDT, THETA-USDT, THG-USDT, TIA-USDT, TON-USDT, TRA-USDT, TRB-USDT, TRX-USDT,TUP-USDT, TURBO-USDT
        UMA-USDT, UNI-USDT, USDC-USDT, USTC-USDT, UTK-USDT, VELO-USDT, VELODROME-USDT, VELA-USDT, VRA-USDT
        VSYS-USDT, WAVES-USDT, WAXP-USDT, WBTC-USDT, WGRT-USDT, WIFI-USDT, WIN-USDT, WLD-USDT, WNCG-USDT
        WOO-USDT, WSB-USDT, WSM-USDT, WXT-USDT, XAUT-USDT, XCH-USDT, XEC-USDT, XEM-USDT, XETA-USDT, XLM-USDT
        XMR-USDT, XNO-USDT, XPR-USDT, XTZ-USDT, YFI-USDT, YFII-USDT, YGG-USDT, ZBC-USDT, ZEC-USDT, ZEN-USDT
        ZIL-USDT, ZKS-USDT, ZRX-USDT
    USDC:
        BTC-USDC, ETH-USDC, OKB-USDC, LTC-USDC, XRP-USDC, BCH-USDC, SOL-USDC, DOGE-USDC, SHIB-USDC, FIL-USDC
        1INCH-USDC, AAVE-USDC, ADA-USDC, AGLD-USDC, ALGO-USDC, ANT-USDC, APE-USDC, APT-USDC, AR-USDC
        ASTR-USDC, ATOM-USDC, AVAX-USDC, BLUR-USDC, BNB-USDC, BSV-USDC, CEL-USDC, CHZ-USDC, COMP-USDC
        CRO-USDC, CRV-USDC, CSPR-USDC, DOT-USDC, DYDX-USDC, EGLD-USDC, EOS-USDC, ETC-USDC,ETHW-USDC
        FLOW-USDC, FLOKI-USDC, FLR-USDC, FTM-USDC, GALA-USDC, GRT-USDC, HBAR-USDC, ICP-USDC, JST-USDC
        KLAY-USDC, KNC-USDC, KSM-USDC, LINK-USDC, LOOKS-USDC, LRC-USDC, LUNC-USDC, LUNA-USDC, MANA-USDC
        MASK-USDC, MATIC-USDC, MINA-USDC, MKR-USDC, NEAR-USDC, OKT-USDC, OP-USDC, RDNT-USDC, RPL-USDC, SAND-USDC
        SNX-USDC, STORJ-USDC, STX-USDC, SUSHI-USDC, TON-USDC, TRX-USDC, UNI-USDC, USDT-USDC, WAVES-USDC
        XLM-USDC, XMR-USDC, YFII-USDC, YGG-USDC, ZEC-USDC, ZIL-USDC
    BTC
        ETH-BTC, OKB-BTC, LTC-BTC, XRP-BTC, BCH-BTC, SOL-BTC, DOGE-BTC, SHIB-BTC, FIL-BTC, AAVE-BTC, ADA-BTC
        ATOM-BTC, AVAX-BTC, BSV-BTC, CHZ-BTC, CRO-BTC, CRV-BTC, DASH-BTC, DOT-BTC, EOS-BTC, ETC-BTC, GRT-BTC
        HBAR-BTC, LINK-BTC, MANA-BTC, MATIC-BTC, MKR-BTC, NEAR-BTC, NEO-BTC, OKT-BTC, QTUM-BTC, STX-BTC
        TRX-BTC, UNI-BTC, WBTC-BTC, XCH-BTC, XLM-BTC, XMR-BTC, ZEC-BTC, ZEN-BTC
    TRY
        USDT-TRY
    DAI
        BTC-DAI, ETH-DAI
    ETH
        OKB-ETH, LTC-ETH, XRP-ETH, SOL-ETH, DOGE-ETH, FIL-ETH, ADA-ETH, ATOM-ETH, BETH-ETH, EOS-ETH
        LINK-ETH, OKT-ETH, STETH-ETH, TRX-ETH, XMR-ETH
    EURT
        BTC-EURT, ETH-EURT
    DOT
        OKDOT2-DOT
"""

auto_reboot = True  # False - показывает ошибки, True - автоматически перезапускается
debug = 'debug'

# Сколько минимально процентов между ступеньками лестницы
step_percent = 1  # %
steps = [(100 + step_percent) * 0.01, (100 - step_percent) * 0.01]

# На сколько процентов уменьшать цену предыдущего ордера
less_percent = 10  # %
less = 1 - (less_percent / 10000)

symbols = ['AVAX-USDT', 'FIL-USDT', 'MATIC-USDT', 'XRP-USDT', 'DYDX-USDT',
           'LUNC-USDT', 'DOT-BTC']

sz_quote = 4.2  # Размер ордера на закуп в USD
tf = '15m'

sleep_1 = 60
sleep_2 = 30
sleep_3 = 10
sleep_4 = 5
